# Generated by Django 2.2.3 on 2020-03-31 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteArticleBak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=25)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'note_article_bak',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=50, verbose_name='类名名')),
                ('desc', models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述')),
                ('type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='note.NoteCategory', verbose_name='父类目级别')),
            ],
            options={
                'db_table': 'note_class',
            },
        ),
        migrations.CreateModel(
            name='NoteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='标题', max_length=50, unique=True, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', help_text='内容', null=True, verbose_name='内容')),
                ('file_name', models.CharField(default='', help_text='文件名', max_length=25, unique=True, verbose_name='文件名')),
                ('create_at', models.DateTimeField(verbose_name='创建时间')),
                ('category', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='note.NoteCategory', verbose_name='文章分类')),
            ],
            options={
                'db_table': 'note_article',
            },
        ),
    ]
