# Generated by Django 2.2.3 on 2020-04-07 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='主题名', max_length=50, verbose_name='主题名')),
                ('desc', models.TextField(blank=True, default='', help_text='主题描述', null=True, verbose_name='主题描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'note_theme',
            },
        ),
        migrations.AlterField(
            model_name='notearticle',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notecategory',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='notecategory',
            name='name',
            field=models.CharField(default='', help_text='类别名', max_length=50, verbose_name='类名'),
        ),
    ]
