# Generated by Django 2.2.3 on 2020-04-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200407_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='notearticle',
            name='theme',
            field=models.ForeignKey(db_column='theme_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='note.NoteTheme', verbose_name='主题分类'),
        ),
    ]
