version: '3.1'

services:
  dns_tools:
    #build: .
    image: harbor.base-fx.com/itd/django:2.2.7
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash start.sh
    restart: unless-stopped
    container_name: dns_tools
    volumes:
      # - ./app:/app
      - /docker_data/django/dns_tools:/app
    ports:
      - "8084:8000"

